name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: |
          cd packages/metals-vscode
          yarn install
      - run: |
          cd packages/metals-vscode
          yarn test

  extension-test:
    name: Extension test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: |
          cd packages/metals-vscode
          yarn install
      - name: Run extension tests
        run: |
          cd packages/metals-vscode
          xvfb-run -a yarn test-extension
        # In headless Linux CI machines xvfb is required to run VS Code
        # https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: |
          cd packages/metals-vscode
          yarn install
      - run: |
          cd packages/metals-vscode
          yarn build

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: |
          cd packages/metals-vscode
          yarn install
      - run: |
          cd packages/metals-vscode
          yarn format-check

  eslint:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: |
          cd packages/metals-vscode
          yarn install
      - run: |
          cd packages/metals-vscode
          yarn eslint .
